title: ElasTest
#baseurl: "/_site" # the subpath of your site, e.g. /blog
url: "http://elastest.io" # the base hostname & protocol for your site, e.g. http://example.com
indexHtml: "index.html"

github_username:  elastest

# Build settings
markdown: kramdown
highlighter: pygments
theme: minima
gems:
  - jekyll-feed
  - jekyll-paginate


exclude:
  - Gemfile
  - Gemfile.lock
  - vendor

paginate: 10 #show N posts
paginate_path: "/blog/page:num/"
#permalink: /:categories/:title
