title: ElasTest
#baseurl: "/_site" # the subpath of your site, e.g. /blog
url: "http://elastest.io" # the base hostname & protocol for your site, e.g. http://example.com
indexHtml: "index.html"

github_username:  elastest

# Build settings
markdown: kramdown
highlighter: pygments
theme: minima
gems:
  - jekyll-feed
  - jekyll-paginate


exclude:
  - Gemfile
  - Gemfile.lock
  - vendor

paginate: 10 #show N posts
paginate_path: "/blog/page:num/"
#permalink: /:categories/:title

authors:
  patxi_gortazar:
    name: Patxi Gortázar
    email: francisco.gortazar@urjc.es
    employer: Universidad Rey Juan Carlos
  micael_gallego:
    name: Micael Gallego
    employer: Universidad Rey Juan Carlos
  antonia_bertolino:
    name: Antonia Bertolino
    employer: Consiglio Nazionale delle Ricerche 
  daniel_ilie:
    name: Ilie-Daniel Gheorghe-Pop
    employer: Fraunhofer FOKUS
  michael_pauls:
    name: Michael Pauls
    employer: Technische Universität Berlin
  cesar_sanchez:
    name: César Sánchez
    employer: IMDEA Software
  felipe_gorostiaga:
    name: Felipe Gorostiaga
    employer: IMDEA Software